// <auto-generated />
namespace FingerTips.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ft : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ft));
        
        string IMigrationMetadata.Id
        {
            get { return "201805262335013_ft"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
